{% set version = "0.4.1" %}

# Explicitly depend on and pin openblas to avoid potential issue as observed
# previously for scikit-umfpack.
# see:  https://github.com/conda-forge/scikit-umfpack-feedstock/issues/8
{% set variant = "openblas" %}

package:
  name: scikit-sparse
  version: {{ version }}

source:
  fn: scikit-sparse-{{ version }}.tar.gz
  url: https://github.com/scikit-sparse/scikit-sparse/archive/v{{ version }}.tar.gz
  sha256: 0af547156b73c83350676474a93fd4613afbabac37a461b6b0e71a06e1a13c65

build:
  skip: True  # [win]
  number: 200
  features:
    - blas_{{ variant }}

requirements:
  build:
    - blas 1.1 {{ variant }}
    - openblas 0.2.19|0.2.19.*
    - python
    - numpy x.x
    - suitesparse
    - cython
    - setuptools
  run:
    - blas 1.1 {{ variant }}
    - openblas 0.2.19|0.2.19.*
    - python
    - numpy x.x
    - scipy
    - suitesparse

test:
  requires:
    - nose
    - setuptools
  imports:
    - sksparse
    - sksparse.cholmod
  commands:
    - OPENBLAS_NUM_THREADS=1 nosetests -sv sksparse

about:
  home: https://github.com/scikit-sparse/scikit-sparse
  license: BSD 2-clause
  summary: A companion to the scipy.sparse library for sparse matrix manipulation in Python.

extra:
    recipe-maintainers:
      - grlee77
      - patricksnape
      - jor-
