{% set version = "0.4.6" %}

package:
  name: scikit-sparse
  version: {{ version }}

source:
  fn: scikit-sparse-{{ version }}.tar.gz
  url: https://github.com/scikit-sparse/scikit-sparse/archive/v{{ version }}.tar.gz
  sha256: 72c436620985cfd0911a6cdb9e691674dafe98dc8bdf4e4a8178d96459554974

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - numpy
    - suitesparse
    - cython
    - setuptools
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy
    - suitesparse

test:
  requires:
    - pytest
    - setuptools
  imports:
    - sksparse
    - sksparse.cholmod
  commands:
    - OPENBLAS_NUM_THREADS=1 pytest --pyargs sksparse

about:
  home: https://github.com/scikit-sparse/scikit-sparse
  license: BSD 2-clause
  license_file: LICENSE.txt
  summary: A companion to the scipy.sparse library for sparse matrix manipulation in Python.

extra:
  recipe-maintainers:
    - grlee77
    - patricksnape
    - jor-
    - jellis18
