{% set version = "0.4.12" %}

package:
  name: scikit-sparse
  version: {{ version }}

source:
  fn: scikit-sparse-{{ version }}.tar.gz
  url: https://github.com/scikit-sparse/scikit-sparse/archive/v{{ version }}.tar.gz
  sha256: f775098160c14162a8388fe0ccc079cc93994fbd57a1dfb3bc89f267189de922
  patches:
    # https://github.com/scikit-sparse/scikit-sparse/pull/84
    - 0001-Fix-import-in-setup.py.patch

build:
  number: 1

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - pip
    - numpy
    - suitesparse
    - cython
    - setuptools
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy
    - suitesparse

test:
  requires:
    - pytest
    - setuptools
  imports:
    - sksparse
    - sksparse.cholmod
  commands:
    - OPENBLAS_NUM_THREADS=1 pytest --pyargs sksparse  # [unix]
    - pytest --pyargs sksparse  # [win]

about:
  home: https://github.com/scikit-sparse/scikit-sparse
  license: BSD-2-Clause
  license_file: LICENSE.txt
  summary: A companion to the scipy.sparse library for sparse matrix manipulation in Python.

extra:
  recipe-maintainers:
    - grlee77
    - patricksnape
    - jor-
    - jellis18
