{% set version = "0.4.3" %}

package:
  name: scikit-sparse
  version: {{ version }}

source:
  fn: scikit-sparse-{{ version }}.tar.gz
  url: https://github.com/scikit-sparse/scikit-sparse/archive/v{{ version }}.tar.gz
  sha256: cbfda3a3b51039b764f3379fa719ec8ed0fd3261d3f0979e6cac9ee8c24993eb

build:
  number: 1
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - numpy
    - suitesparse
    - cython
    - setuptools
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy
    - suitesparse

test:
  requires:
    - nose
    - setuptools
  imports:
    - sksparse
    - sksparse.cholmod
  commands:
    - OPENBLAS_NUM_THREADS=1 nosetests -sv sksparse

about:
  home: https://github.com/scikit-sparse/scikit-sparse
  license: BSD 2-clause
  summary: A companion to the scipy.sparse library for sparse matrix manipulation in Python.

extra:
    recipe-maintainers:
      - grlee77
      - patricksnape
      - jor-
