travis:
  secure:
    BINSTAR_TOKEN: u+p5jS+DU64C4fyjfkOYIA8skvMdnXRX1sRP5PnApUpFzMxpHopD5wFNm8IMa1PS2zC3JdxVPG8MMVVKODOAiy9l9WqtUzzbSMU5kfxHP2uTc7YDrTUfccWsl0/78PVskwikyVFqJe6rTlhmqJZlajehEdHGYljYqIAuFre8gYadRVuiMzURoRwB5x/YhiOWEJvchDc/KqtYWUyPW/xSKkghlkYYRSQTddD+rKYkE9tKj7ONtSYnGKkwNXQ6EkUoDnuww3ius+Seai5nUm7C1WrQURkRnZ+0IuskFylkWlve0D+U5rOUiqmwR7QE2pA+RURztJxyD+meSvKt97VhUr7owXlQN+q0fy5uZjYHmYW8NIMKgxsKVeUUdAwgvqT869sYhfQOrm2GsyEEjSkND7m9MWkbSqW0Fx5p+zqE+hkZH3LoINccDLYVvySfUt098QglfgngxQjvhB2PR8akjStGBGpQOApF7wQ4lxEY3TFVsEfgRLJwZagxlWCSdCRsxhVL9QFkECGdPt/AtuKQNotq9TZ6TNgOpi2Sx60EdHBkEFMae0MOGvzIt9Y7crQNxkSprgwjrv3myzbQqOYpWG9An5akOUSEjvASS/nnKF3nUPmMwJglfRr5zmuq/V68QmSns2mJY/DdrJ1iSRjp6qWM8W0dc5epmUcDjQ1bU7M=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
